# Generated by Django 5.2.4 on 2025-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fungo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametroMIN', models.IntegerField()),
                ('diametroMAX', models.IntegerField()),
                ('altezzaMIN', models.IntegerField()),
                ('altezzaMAX', models.IntegerField()),
                ('altitudineMIN', models.IntegerField()),
                ('altitudineMAX', models.IntegerField()),
                ('mesi', models.JSONField()),
                ('valori', models.JSONField()),
            ],
        ),
    ]
