# Generated by Django 5.2.4 on 2025-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Valore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='fungo',
            name='mesi',
        ),
        migrations.RemoveField(
            model_name='fungo',
            name='valori',
        ),
        migrations.AddField(
            model_name='fungo',
            name='mesi',
            field=models.ManyToManyField(null=True, related_name='funghi', to='main.mese'),
        ),
        migrations.AddField(
            model_name='fungo',
            name='valori',
            field=models.ManyToManyField(null=True, related_name='funghi', to='main.valore'),
        ),
    ]
