# Generated by Django 5.2.4 on 2025-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mese_valore_remove_fungo_mesi_remove_fungo_valori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungo',
            name='mesi',
            field=models.ManyToManyField(related_name='funghi', to='main.mese'),
        ),
        migrations.AlterField(
            model_name='fungo',
            name='valori',
            field=models.ManyToManyField(related_name='funghi', to='main.valore'),
        ),
    ]
